services:
  bryanveloso:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: bryanveloso
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    restart: unless-stopped

  avalonstar:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: avalonstar
    ports:
      - "4322:4321"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    restart: unless-stopped

  omnyist:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: omnyist
    ports:
      - "4323:4321"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    restart: unless-stopped
