services:
  bryanveloso:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: bryanveloso
    ports:
      - '4321:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  avalonstar:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: avalonstar
    ports:
      - '4322:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  omnyist:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: omnyist
    ports:
      - '4323:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
