services:
  bryanvelo.so:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: bryanvelo.so
    ports:
      - '4321:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000').then(() => process.exit(0)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

  avalonstar.com:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: avalonstar.com
    ports:
      - '4322:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000').then(() => process.exit(0)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  omnyist.com:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: omnyist.com
    ports:
      - '4323:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000').then(() => process.exit(0)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  avalonstar.tv:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        APP_NAME: avalonstar.tv
    ports:
      - '4324:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000').then(() => process.exit(0)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
