name: Deploy
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [content-update]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images
        run: |
          cd ${{ github.workspace }}
          SITE="${{ github.event.client_payload.site }}"
          if [ "$SITE" != "" ]; then
            docker compose build --build-arg CACHEBUST=$(date +%s) $SITE
          else
            docker compose build
          fi

      - name: Deploy
        run: |
          cd ${{ github.workspace }}
          SITE="${{ github.event.client_payload.site }}"
          if [ "$SITE" != "" ]; then
            docker compose up -d $SITE
          else
            docker compose up -d
          fi
          docker image prune -f
