name: Deploy
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [content-update]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images
        run: |
          cd ${{ github.workspace }}
          if [ "${{ github.event.client_payload.site }}" != "" ]; then
            docker compose build ${{ github.event.client_payload.site }}
          else
            docker compose build
          fi

      - name: Deploy
        run: |
          cd ${{ github.workspace }}
          if [ "${{ github.event.client_payload.site }}" != "" ]; then
            docker compose up -d ${{ github.event.client_payload.site }}
          else
            docker compose up -d
          fi
          docker image prune -f
