name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images
        run: |
          cd ${{ github.workspace }}
          docker compose build

      - name: Deploy
        run: |
          cd ${{ github.workspace }}
          docker compose up -d
          docker image prune -f
